### ISSUE TITLE
Infografia AR

### ISSUE THREAD

**Issue by AxayacatlS** [SistemasTecTlaxiaco/infografia-AxayacatlS#1]
Infografía de Realidad Aumentada y Realidad Virtual
![AR y VR Infografías](https://user-images.githubusercontent.com/38516115/110083350-3384d400-7d54-11eb-99c0-43b6ed51cf41.jpg)

**Comment by ObedG** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
